services:
  runner:
    image: gitea/act_runner:latest
    environment:
      CONFIG_FILE: config.yaml
      GITEA_INSTANCE_URL: [URL]
      GITEA_RUNNER_REGISTRATION_TOKEN: [TOKEN]
      GITEA_RUNNER_NAME: [RUNNER]
      GITEA_RUNNER_LABELS: [LABEL]
    volumes:
      - ./runner-config:/config
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/andrei/docker/runner-config/startup.sh:/opt/startup.sh
    restart: always
    command: sh -c "apk add --no-cache nodejs npm bash git && /entrypoint.sh"
    privileged: true