jpackage --type deb \
    --name "FromGtoG" \
    --vendor "Andrei Dodu" \
    --app-version "6.0.13" \
    --input "target" \
    --main-jar "fromgtog.jar" \
    --main-class "com.andreidodu.fromgtog.Main" \
    --dest "executable" \
    --add-modules java.base,java.desktop,java.net.http,java.naming,java.sql \
    --linux-shortcut \
    --verbose
