jpackage --type exe \
    --name "FromGtoG" \
    --vendor "Andrei Dodu" \
    --app-version "6.0.13" \
    --input "target/fromgtog.jar" \
    --main-jar "fromgtog.jar" \
    --main-class "com.andreidodu.fromgtog.Main" \
    --dest "executable" \
    --add-modules java.base,java.desktop,java.net.http,java.naming,jdk.unsupported \
    --icon "path/to/your/icon.ico" \
    --win-menu \
    --win-shortcut \
    --win-console \
    --verbose