name: fromgtog
version: '10.0.7'
summary: Advanced utility for Git backup and bulk migration(GitHub,Gitea,GitLab,Local)
description: |
  Advanced cross-platform utility for Git backup and bulk migration.
grade: stable
confinement: strict
base: core24
icon: snap/gui/icon.png
title: FromGtoG
website: https://andre-i.eu
issues: https://github.com/goto-eof
source-code: https://github.com/goto-eof/fromgtog
donation: https://github.com/sponsors/goto-eof
contact: https://andre-i.eu/#contactme
compression: lzo
license: CC-BY-NC-4.0
slots:
  fromgtog-dbus:
    interface: dbus
    bus: session
    name: it.es5.fromgtog.dbus
apps:
  fromgtog:
    environment:
      ALSA_CONFIG_PATH: $SNAP/etc/asound.conf
      GIO_EXTRA_MODULES: $GIO_EXTRA_MODULES:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/gio/modules
      LD_LIBRARY_PATH: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/alsa-lib:$LD_LIBRARY_PATH
    command: usr/bin/run.sh
    extensions: [ gnome ]
    plugs:
      - audio-playback
      - browser-support
      - home
      - network
      - network-bind
      - unity7
      - wayland
      - x11
      - desktop
platforms:
  amd64:
    build-on: [ amd64 ]
    build-for: [ amd64 ]
  arm64:
    build-on: [ arm64 ]
    build-for: [ arm64 ]
parts:
  copy-required-files:
    plugin: dump
    source: snap/local
    source-type: local
    organize:
      build.sh: usr/lib/build.sh
      prime.sh: usr/lib/prime.sh
      run.sh: usr/bin/run.sh
      asound.conf: etc/asound.conf
    prime:
      - usr/lib/build.sh
      - usr/lib/prime.sh
      - usr/bin/run.sh
      - etc/asound.conf
  application:
    plugin: maven
    source: .
    build-packages:
      - openjdk-21-jdk
      - maven
    after:
      - copy-required-files
    stage-packages:
      - openjdk-21-jre
      - glib-networking
      # os actions like open browser
      - xdg-utils
      # app indicator
      - librsvg2-common
      # sound
      - alsa-utils
      - libasound2-plugins
      - libasound2
      - liboss4-salsa-asound2
    override-prime: |
      . $SNAPCRAFT_STAGE/usr/lib/prime.sh
      snapcraftctl prime