name: CI/CD - Create MacOS DMG file

on:
  push:
    tags:
      - '*'

jobs:
  build_jar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configura JDK (Linux)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build JAR with Maven
        run: mvn clean package

      - name: Load Artifact (JAR and resources)
        uses: actions/upload-artifact@v4
        with:
          name: application-files
          path: |
            target/fromgtog.jar
            resources/

  create_dmg:
    runs-on: windows-latest
    permissions:
      contents: write
    needs: build_jar
    steps:
      - uses: actions/checkout@v4
      - name: Define release version
        id: set_version
        shell: pwsh
        run: |
          Write-Host "Files:"
          Get-ChildItem -Recurse
          echo "RELEASE_TAG=${{ github.ref_name }}" >> $env:GITHUB_ENV
          Write-Host "Release Tag set on: ${{ github.ref_name }}"
      - name: Download Artifact (JAR and resources)
        uses: actions/download-artifact@v4
        with:
          name: application-files
          path: downloaded-files

      - name: Configure JDK for Windows
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Create DMG file with jpackage
        run: |
          $InputPath = "downloaded-files\target"
          $OutputPath = "executable"
          $MainJar = "fromgtog.jar"
          $IconPath = "downloaded-files\resources\icon-mac.icns"
          jpackage --input "$INPUT_PATH" --dest "$OUTPUT_PATH" --name "FromGtoG" --vendor "Andrei Dodu" --app-version "$RELEASE_TAG" --main-jar "$MAIN_JAR" --main-class com.andreidodu.fromgtog.Main --icon "$ICON_PATH" --type dmg --mac-package-identifier "com.andreidodu.fromgtog" --java-options "-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true" --add-modules java.base,java.desktop,java.net.http,java.naming,java.sql,java.management,java.security.jgss,java.xml,java.logging,jdk.crypto.ec,java.security.sasl --verbose

      - name: Zip DMG file
        shell: pwsh
        run: |
          $SourcePath = "executable\FromGtoG-$env:RELEASE_TAG.dmg" 
          $DestinationName = "${{ github.event.repository.name }}-MacOS-${{ github.ref_name }}-arm64.zip"
          Compress-Archive -Path $SourcePath -DestinationPath $DestinationName
      - name: Release on Github
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{github.event.repository.name}}-MacOS-${{ github.ref_name }}-arm64.zip
