name: CI/CD - Create Windows DEB file

on:
  push:
    tags:
      - '*'

jobs:
  build_jar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configura JDK (Linux)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build JAR with Maven
        run: mvn clean package

      - name: Load Artifact (JAR and resources)
        uses: actions/upload-artifact@v4
        with:
          name: application-files
          path: |
            target/fromgtog.jar
            resources/

  create_deb:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    needs: build_jar
    steps:
      - uses: actions/checkout@v4

      - name: Define release version
        run: |
          echo "RELEASE_TAG=${GITHUB_REF_NAME}" >> $GITHUB_ENV
          echo "Release Tag set on: ${GITHUB_REF_NAME}"

      - name: Download Artifact (JAR and resources)
        uses: actions/download-artifact@v4
        with:
          name: application-files
          path: downloaded-files

      - name: Configure JDK for Debian
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install jpackage dependencies (Debian)
        run: |
          sudo apt-get update
          sudo apt-get install -y fakeroot dpkg-dev libfuse2

      - name: Create DEB package with jpackage
        run: |
          INPUT_PATH="downloaded-files/target"
          OUTPUT_PATH="executable"
          MAIN_JAR="fromgtog.jar"
          ICON_PATH="downloaded-files/resources/icon-linux.png"
          mkdir -p "$OUTPUT_PATH"
          jpackage \
            --input "$INPUT_PATH" \
            --dest "$OUTPUT_PATH" \
            --name "FromGtoG" \
            --vendor "Andrei Dodu" \
            --app-version "$RELEASE_TAG" \
            --main-jar "$MAIN_JAR" \
            --main-class com.andreidodu.fromgtog.Main \
            --icon "$ICON_PATH" \
            --type deb \
            --linux-shortcut \
            --linux-menu-group "FromGtoG" \
            --java-options "-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true" \
            --add-modules java.base,java.desktop,java.net.http,java.naming,java.sql,java.management,java.security.jgss,java.xml,java.logging,jdk.crypto.ec,java.security.sasl \
            --verbose

      - name: Zip DEB package
        run: |
          SOURCE_PATH=$(find executable -name "*.deb" | head -n 1)
          DEST_NAME="${{ github.event.repository.name }}-${{ github.ref_name }}-Debian-Installer.zip"
          zip -j "$DEST_NAME" "$SOURCE_PATH"

      - name: Release on GitHub
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ github.event.repository.name }}-${{ github.ref_name }}-Debian-Installer.zip
