name: Create JAR file

on:
  push:
    tags:
      - '*'

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: code checkout
        uses: actions/checkout@v4

      - name: JDK setup
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: compile and test
        run: mvn -B verify --file pom.xml

      - name: create jar
        run: mvn -B package --file pom.xml

      - name: upload jar
        uses: actions/upload-artifact@v4
        with:
          name: application-files
          path: target/fromgtog.jar
          retention-days: 5

      - name: Download Artifact (JAR and resources)
        uses: actions/download-artifact@v4
        with:
          name: application-files
          path: downloaded-files

      - name: Release on GitHub
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: application-files/fromgtog.jar#${{ github.event.repository.name }}-${{ github.ref_name }}.jar
