# disabled because currently GitHub does not allow ARM builds for Linux

name: Do Nothing

on:
  push:
    tags:
      - '*'

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - name: Do nothing
        run: echo "Nothing to do here!"

#name: CI/CD - Create Linux ARM64 DEB file
#
#on:
#  push:
#    tags:
#      - '*'
#
#jobs:
#  build_jar:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#
#      - name: Configure JDK (Linux ARM)
#        uses: actions/setup-java@v4
#        with:
#          distribution: 'temurin'
#          java-version: '21'
#
#      - name: Build JAR with Maven
#        run: mvn clean package
#
#      - name: Upload Artifact (JAR and resources)
#        uses: actions/upload-artifact@v4
#        with:
#          name: application-files
#          path: |
#            target/fromgtog.jar
#            resources/
#
#  create_deb_arm:
#    runs-on: ubuntu-24.04-arm64
#    permissions:
#      contents: write
#    needs: build_jar
#    steps:
#      - uses: actions/checkout@v4
#
#      - name: Define release version
#        id: set_version
#        run: |
#          echo "RELEASE_TAG=${GITHUB_REF_NAME}" >> $GITHUB_ENV
#          echo "Release Tag set on: ${GITHUB_REF_NAME}"
#
#      - name: Download Artifact (JAR and resources)
#        uses: actions/download-artifact@v4
#        with:
#          name: application-files
#          path: downloaded-files
#
#      - name: Configure JDK for Linux ARM
#        uses: actions/setup-java@v4
#        with:
#          distribution: 'temurin'
#          java-version: '21'
#
#      - name: Install required dependencies for jpackage
#        run: |
#          sudo apt-get update
#          sudo apt-get install -y fakeroot dpkg-dev zip
#
#      - name: Create ARM DEB package with jpackage
#        run: |
#          INPUT_PATH="downloaded-files/target"
#          OUTPUT_PATH="executable"
#          MAIN_JAR="fromgtog.jar"
#          ICON_PATH="downloaded-files/resources/icon-linux.png"
#
#          mkdir -p "$OUTPUT_PATH"
#
#          jpackage \
#            --input "$INPUT_PATH" \
#            --dest "$OUTPUT_PATH" \
#            --name "FromGtoG" \
#            --vendor "Andrei Dodu" \
#            --app-version "$RELEASE_TAG" \
#            --main-jar "$MAIN_JAR" \
#            --main-class com.andreidodu.fromgtog.Main \
#            --icon "$ICON_PATH" \
#            --type deb \
#            --linux-shortcut \
#            --java-options "-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true" \
#            --add-modules java.base,java.desktop,java.net.http,java.naming,java.sql,java.management,java.security.jgss,java.xml,java.logging,jdk.crypto.ec,java.security.sasl \
#            --verbose
#
#      - name: Zip DEB file (ARM)
#        run: |
#          DEB_FILE=$(ls executable/*.deb | head -n 1)
#          ZIP_NAME="${{ github.event.repository.name }}-Linux-${{ github.ref_name }}-arm64-Installer.zip"
#          zip -j "$ZIP_NAME" "$DEB_FILE"
#
#      - name: Release on GitHub
#        uses: softprops/action-gh-release@v1
#        if: startsWith(github.ref, 'refs/tags/')
#        with:
#          files: ${{ github.event.repository.name }}-Linux-${{ github.ref_name }}-arm64-Installer.zip
